# Generated by Django 6.0.7 on 2026-07-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_prefix', models.CharField(blank=True, help_text='e.g. "From" for starting-at pricing', max_length=20)),
                ('unit', models.CharField(choices=[('day', 'Day'), ('event', 'Event'), ('project', 'Project')], default='day', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlights this card, e.g. "Most booked"')),
                ('badge_text', models.CharField(blank=True, default='Most booked', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.serviceplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
