# Generated by Django 6.0.7 on 2026-07-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
    ]
