# Generated by Django 6.0.7 on 2026-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='portfolio_items', to='gallery.tag'),
        ),
    ]
