# Generated by Django 6.0.7 on 2026-07-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_checkout_session_id',
            new_name='gateway_session_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='gateway_transaction_id',
        ),
    ]
